# Generated by Django 4.2 on 2023-05-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_datecomleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomleted',
            new_name='datecompleted',
        ),
    ]
